### ISSUE TITLE
Chrome extensions inline install link doesn't work

### ISSUE THREAD

**Issue by fjaguero** [DerMambo/ms-seo#45]
Hello,

It looks like the package is removing/updating the <link> tag that is needed to install a [Chrome install via webpage](https://developer.chrome.com/webstore/inline_installation). After removing the package, the inline extension works as expected.

How can I set this tag manually or how can we avoid this tag (rel='chrome-webstore-item') to be deleted?

Thanks.

**Comment by DerMambo** [comment]
Try using the ignore option:

```
SEO =
  settings: {
    title: ''
    rel_author: ''
    meta: []
    og: []
    twitter: []
    ignore:
      meta: ['fragment'],
      link: ['stylesheet', 'icon', 'apple-touch-icon'],
      rel: ['chrome-webstore-item']
    auto:
      twitter: true
      og: true
      set: ['description', 'url', 'title']
  }
```
Does this help?

**Comment by fjaguero** [comment]
I just opened the issue to write the exact solution. Just saw the SEO.ignore method.

```javascript
SEO.ignore('link', 'chrome-webstore-item');
```

Thanks for the fast answer.

**Comment by fjaguero** [comment]
Maybe it's a good idea to add a small paragraph on the README regarding the ignore method.
