### ISSUE TITLE
Uncaught TypeError: Cannot set property 'content' of null detector.js:450

### ISSUE THREAD

**Issue by stephentcannon** [DerMambo/ms-seo#5]
Uncaught TypeError: Cannot set property 'content' of null detector.js:450
(anonymous function) detector.js:450
(anonymous function) detector.js:456

  // convert to array
  var jsonString = JSON.stringify(_apps);
  // send back to background page
  var meta = document.getElementById('chromesniffer_meta');
  meta.content = jsonString;

**Comment by rafaelfaria** [comment]
I'm getting the same error after installing ms-seo package.
