### ISSUE TITLE
Seo set title on the iron:router dataNotFound

### ISSUE THREAD

**Issue by jmlv** [DerMambo/ms-seo#55]
Hey!
How to add title on the dataNotFound plugin?

console tells me:
    
    Exception from Tracker recompute function: debug.js:41 TypeError: Cannot read property 'getName' of undefined

I have some config:

    Meteor.startup(function() {
        if (Meteor.isClient) {
        return SEO.config({
            title: "someTitle",
            meta: {
                "description": "someDesc"
            }
        });
        }
    });

**Comment by meteor-software** [comment]
I had the same issue.

Try to add special route for dataNotFound template. It works fine for me.
``` javascript
Router.route("/(.*)", {
    name: "notFound"
});
```

**Comment by jmlv** [comment]
Big thanks, @meteor-software
