### ISSUE TITLE
Does this create the "twitter:card" tag automatically

### ISSUE THREAD

**Issue by abhirakshit** [DerMambo/ms-seo#63]
Hello,

I am using this library in my project and I can see the twitter:title and twitter:url correctly in the meta tags but no twitter:card tag.

Does the library support the card tag? If yes is there something specific I need to do to get it?

I have this added to my config - 
```javascript
auto: {
                twitter: true,
                og: true,
                set: ['description', 'url', 'title']
            },
```

**Comment by SachaG** [comment]
You can use Twitter cards like this:

```js
var props = {meta: {}, og: {}, twitter: {}};
props.twitter.card = "summary_large_image";
props.twitter.image = "http://mysite.com/image.jpg";
SEO.set(props);
```

**Comment by abhirakshit** [comment]
Thanks Sacha that worked for me.
